### ISSUE TITLE
Pantalla de Ver Perfil

### ISSUE THREAD

**Issue by cmatuteec** [bram70/viewflow-crece#145]
En esta parte, el usuario inversionista podrá modificar su información.
1.- Información personal

- [x] Se incluye la información de _Datos personales_ y _Domicilio del formulario de inversionista_ en la Pantalla 8 del issue #116 

- [x] Cuando el inversionista tenga el estado de No confirmado, toda la información puede ser editada.

- [x] Cuando el inversionista tenga el estado de Confirmado, no se podrá editar usuario/correo electrónico, nombres, apellidos, número de cédula.

- [x] Añadir luego botón **Guardar**

- [x] Añadir en la parte superior palabra Editar con icono de lápiz, al dar clic allí se habilita la opción de editar información.

- [x] Se incluye la posibilidad de añadir una imagen a su perfil. En la versión móvil, habilitar la posibilidad de tomar foto.
![image](https://user-images.githubusercontent.com/61850215/93972788-951e2c80-fd38-11ea-9ab9-290338a87793.png)

2.- Información laboral

- [x] Se incluye la información de _Fuentes de ingresos_ del formulario de inversionista en la Pantalla 8 del issue #116 

- [x] En el caso de usuario independiente:

- [x] Cuando el inversionista tenga el estado de No confirmado, toda la información puede ser editada.

- [x] Cuando el inversionista tenga el estado de Confirmado, no se podrá editar el número de RUC

- [x] Añadir en la parte superior palabra Editar con icono de lápiz, al dar clic allí se habilita la opción de editar información.

![image](https://user-images.githubusercontent.com/61850215/91218386-924efe00-e6de-11ea-8d29-60fde4b25f66.png)

3.- Cuenta bancaria

- [x] Se incluye la información de _Registra tu cuenta bancaria donde recibirás tus ganancias_ del formulario de inversionista en la Pantalla 8 del issue #116

- [x] No se puede editar el campo de _Titular_ se asume que el titular de la cuenta es el mismo usuario y esa información no se cambia. Esto va atado a corregir el formulario de la pantalla 8 del issue #116 donde se copia automáticamente en el campo de _Titular_ los nombres y apellidos. No se puede ingresar una cuenta donde el titular sea otra persona.

- [x] Añadir en la parte superior palabra Editar con icono de lápiz, al dar clic allí se habilita la opción de editar información.

![image](https://user-images.githubusercontent.com/61850215/91219110-bd861d00-e6df-11ea-9758-b6deb6fa8645.png)

4.- Contratos aceptados

- [x] Se muestra una tabla de dos columnas.

- [x] Columna 1 enlista todos los contratos aceptados en formato de link que permita al usuario abrir el contrato en una pestaña nueva.

- [x] Contratos a mostrar:

Términos y condiciones
Políticas de privacidad
Acuerdos de inversionista (En caso que este acuerdo cambie, se añadirá en el futuro una pantalla donde se pida aceptar el nuevo acuerdo de inversionista)
Declaración de origen de fondos

- [x] Columna 2 muestra la fecha en que se aceptó el respectivo contrato.

![image](https://user-images.githubusercontent.com/61850215/91219271-f58d6000-e6df-11ea-9bb4-6a14b8270661.png)

6.- Cambiar contraseña

- [ ] Permite al usuario realizar el cambio de su contraseña.
